services:
  mongo:
    image: mongo:6.0
    container_name: esr-indexing-v2-mongo
    environment:
      MONGO_INITDB_DATABASE: esr-lab-v2
    ports:
      - "27019:27017"
    volumes:
      - mongo_v2_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_v2_data:
